name = "trading-edu-bot-worker"
main = "src/index.js"
compatibility_date = "2025-09-10"
account_id = "f926e63933e4c6bf7eb3eb502955dfc7"

# Common settings
workers_dev = true

# Cron trigger
[triggers]
crons = ["0 * * * *"]

# Routes for the UI
routes = [
  { pattern = "trading-edu-bot.tradermindai.workers.dev", custom_domain = true }
]

# Development environment
[env.dev]
name = "trading-edu-bot-worker-dev"
vars = { 
  LOG_LEVEL = "debug",
  POST_FREQUENCY = "0 * * * *"
}

# Production environment
[env.production]
name = "trading-edu-bot-worker"
vars = { 
  LOG_LEVEL = "info",
  POST_FREQUENCY = "0 * * * *"
}

# Static assets handling
[site]
bucket = "./src/ui"
