name = "trading-edu-bot-worker"
main = "src/index.js"
compatibility_date = "2025-09-10"
account_id = "f926e63933e4c6bf7eb3eb502955dfc7"

workers_dev = true

[triggers]
crons = ["*/10 * * * *"]

[[kv_namespaces]]
binding = "SUBJECTS_QUEUE"
id = "c6534dacb0974cdf904226d915f1aca5"

[env.dev]
name = "trading-edu-bot-worker-dev"

[env.dev.vars]
LOG_LEVEL = "debug"
POST_FREQUENCY = "0 * * * *"
# Define in .dev.vars or set via wrangler secret
# TELEGRAM_BOT_TOKEN = "your-token"
# TELEGRAM_CHAT_ID = "your-chat-id"
# ADMIN_TOKEN = "your-admin-token"
# Optional: OPENROUTER_API_KEY = "your-openrouter-key"

[env.production]
name = "trading-edu-bot-worker"

[env.production.vars]
LOG_LEVEL = "info"
POST_FREQUENCY = "0 * * * *"
# Define in .prod.vars or set via wrangler secret
# TELEGRAM_BOT_TOKEN = "your-token"
# TELEGRAM_CHAT_ID = "your-chat-id"
# ADMIN_TOKEN = "your-admin-token"
# Optional: OPENROUTER_API_KEY = "your-openrouter-key"
